CREATE TABLE `table_1` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `测量均值` decimal(8,5) NOT NULL,
  `READFLAG` int(2) NOT NULL,
  `记录时间` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

CREATE TABLE `table_2` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `校准值` decimal(8,5) NOT NULL,
  `记录时间` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

CREATE TABLE `table_3` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `速度` decimal(8,2) NOT NULL,
  `READFLAG` int(2) NOT NULL,
  `记录时间` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

CREATE TABLE `table_4` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `出土速度` decimal(8,5) NOT NULL,
  `记录时间` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;
